/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef WORD-GUESS_PRIVATE_H
#define WORD-GUESS_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.2.4.164"
#define VER_MAJOR	1
#define VER_MINOR	2
#define VER_RELEASE	4
#define VER_BUILD	164
#define COMPANY_NAME	""
#define FILE_VERSION	"1.2.4.164"
#define FILE_DESCRIPTION	"Word-Guess Main Program"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Word-Guess Game"
#define PRODUCT_VERSION	"1.2.4.164"

#endif /*WORD-GUESS_PRIVATE_H*/
