/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef WORD-GUESS_PRIVATE_H
#define WORD-GUESS_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.3.136"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	3
#define VER_BUILD	136
#define COMPANY_NAME	""
#define FILE_VERSION	"1.1.3.136"
#define FILE_DESCRIPTION	"Word-Guess Main Program"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Word-Guess Game"
#define PRODUCT_VERSION	"1.1.3.136"

#endif /*WORD-GUESS_PRIVATE_H*/
